from fpdf import FPDF
from datetime import date


class PDF(FPDF):
    def header(self):
        self.set_font("Arial", "B", 16)
        self.cell(0, 10, "NSU DEGREE AUDIT REPORT", 0, 1, "C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(
            0,
            10,
            f"Page {self.page_no()}/{{nb}} - Generated by Enterprise Audit System",
            0,
            0,
            "C",
        )

    def draw_progress_bar(self, x, y, w, h, percent):
        # Background (Grey)
        self.set_fill_color(230, 230, 230)
        self.rect(x, y, w, h, "F")
        # Foreground (Green or Red)
        if percent < 0.5:
            self.set_fill_color(220, 53, 69)  # Red
        elif percent < 0.8:
            self.set_fill_color(255, 193, 7)  # Yellow
        else:
            self.set_fill_color(40, 167, 69)  # Green

        fill_width = w * percent
        self.rect(x, y, fill_width, h, "F")

        # Border
        self.set_draw_color(0, 0, 0)
        self.rect(x, y, w, h, "D")


def generate_pdf(
    student_name,
    program,
    cgpa,
    earned_credits,
    total_needed,
    deficiencies,
    filename="Audit_Report.pdf",
):
    pdf = PDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    # 1. Student Info Box
    pdf.set_font("Arial", "", 12)
    pdf.set_fill_color(240, 248, 255)  # Light Blue
    pdf.rect(10, 30, 190, 30, "F")

    pdf.set_xy(15, 35)
    pdf.cell(90, 10, f"Student: {student_name}", 0, 0)
    pdf.cell(90, 10, f"Program: {program}", 0, 1)
    pdf.set_x(15)
    pdf.cell(90, 10, f"Date: {date.today()}", 0, 0)
    pdf.cell(90, 10, f"Status: {'PROBATION' if cgpa < 2.0 else 'Good Standing'}", 0, 1)
    pdf.ln(10)

    # 2. Visual Progress Section
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Degree Progress", ln=True)

    # Calculate Percentage
    if total_needed == 0:
        total_needed = 130  # Default fallback
    percent = min(earned_credits / total_needed, 1.0)

    # Draw Bar
    pdf.draw_progress_bar(10, pdf.get_y() + 2, 190, 10, percent)
    pdf.ln(15)
    pdf.set_font("Arial", "", 10)
    pdf.cell(
        0,
        5,
        f"{earned_credits} credits earned out of {total_needed} required ({int(percent*100)}%)",
        ln=True,
        align="C",
    )
    pdf.ln(10)

    # 3. CGPA Section
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Academic Performance", ln=True)
    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 10, f"Current CGPA: {cgpa:.2f}", ln=True)
    pdf.ln(5)

    # 4. Deficiency Report
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Deficiency Report (Action Items)", ln=True)
    pdf.set_font("Arial", "", 11)

    if not deficiencies:
        pdf.set_text_color(0, 128, 0)  # Green
        pdf.cell(0, 10, "No Deficiencies Found. ELIGIBLE FOR GRADUATION.", ln=True)
    else:
        pdf.set_text_color(200, 0, 0)  # Red
        for reason in deficiencies:
            pdf.cell(0, 8, f"- {reason}", ln=True)

    # 5. Interactive Footer Link
    pdf.ln(15)
    pdf.set_text_color(0, 0, 255)
    pdf.set_font("Arial", "U", 11)
    # Add a clickable mailto link
    pdf.cell(
        0,
        10,
        "Click here to email your Advisor about these results",
        ln=True,
        align="C",
        link="mailto:advisor@northsouth.edu",
    )

    pdf.output(filename)
    return filename
